version: '3'

services:
    database:
        image: mysql:8.0.19
        ports:
            - "3310:3306"
        volumes:
            - numenorian_rage:/var/lib/mysql
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
    numenorian_rage:
